### ISSUE TITLE
Review  https://www.useloom.com

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/MiscLegal#10]
@robmyers @jayaw 

For tracking. Happy to talk, too.

**Comment by robmyers** [comment]
I took a look.

* Their privacy policy is here:

https://www.useloom.com/privacy

* Their Chrome extension asks for lots of permissions but that's standard for anything that wants to record desktop video.

* We can sign up with our cc.org email accounts but there is not an organisational security model -
 we cannot set videos to be "viewable only by people logged in with cc.org emails", for example. Videos can be viewed either by people with a link to the video, or with a password (which I don't recommend as generating and remembering them would be too much to manage). So we would need to be careful not to share links to videos outside the organisation. I'd prefer something more secure but I think this is tolerable.

* I had trouble connecting my video camera but that's my video camera, not the plugin. The video recorded well and was available to view and share immediately.
