### ISSUE TITLE
add summary of Spirit Legal case to caselaw wiki

### ISSUE THREAD

**Issue by tvol** [creativecommons/MiscLegal#6]
http://arstechnica.co.uk/tech-policy/2016/12/commercial-sites-must-check-all-their-links-for-piracy-rules-hamburg-court/

https://www.spiritlegal.com/files/userdata_global/downloads/LG%20Hamburg,%20Beschluss%20vom%2018.11.2016,%20310%20O%2040216.pdf

**Comment by peterspdx** [comment]
awesome, thanks for the reminder Tim. We still have to add the great minds
litigation piece, but had been waiting on a decision on the amicus.

Diane M. Peters
General Counsel, Creative Commons
Portland, Oregon
http://creativecommons.org/staff#dianepeters
13:00-21:00 UTC

**Comment by sarahpearson** [comment]
Added this to the wiki here: https://wiki.creativecommons.org/wiki/Spirit

The party names are redacted, so I wasn't sure of the name of the case. Spirit Legal is the name of the law firm representing the plaintiff, so that's what I used.
