### ISSUE TITLE
Add errata for CC0 to wiki

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/MiscLegal#9]
On this page:
https://wiki.creativecommons.org/wiki/Legalcode_errata

Add an entry for CC0 (currently, only license errata are listed), and note the following error:

In paragraph 4.b., "or the present or absence of errors" should read "or the presence or absence of errors" (misspelling of presence).

Let me know if you have questions. Thanks!

**Comment by georgehari** [comment]
The errata is already there: https://wiki.creativecommons.org/wiki/Legalcode_errata#CC0_.281.0.29
